<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT00TVxz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT00TVxz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT00TVxz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT00TVxz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT00TVxz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T00TVxz',
    'container.build_id' => '2b66e10a',
    'container.build_time' => 1610138746,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT00TVxz');
